<?php
/**
 * Zikula Application Framework
 *
 * @copyright (c) 2001, Zikula Development Team
 * @link http://www.zikula.org
 * @version $Id: pnuser.php 31 2008-12-23 20:55:41Z Guite $
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 */
 
function catalogo_user_main($args=array())
{	
	// Obtener la categoría que se requier cargar (desde la url)
	$item = FormUtil::getPassedValue('item', (isset($args['item'])) ? $args['item'] : 'petit', 'GET');
	
	// Convertir de formato URL a común (Pasar a userapi)
	$item = strtr($item, "-", " ");
	
	// Obtener los datos del producto
	$pntable = pnDBGetTables();
    $catalogo = $pntable['catalogo_column'];
	$dat = DBUtil::selectObjectByID('catalogo', $item, 'name');
	
	// Obtener los datos de todos los productos de la misma categoría
	$dats = array();
    $where = "WHERE $catalogo[cat] = '" . pnVarPrepForStore($dat['cat']) . "'";
	$orderBy = "ORDER BY $catalogo[code]";
    $dats = DBUtil::selectObjectArray ('catalogo', $where, $orderBy);
	
	foreach ($dats as $key => $value)
	{
		if ($value['name'] == $dat['name'])
		{
			if ($key != 0) $dat['past'] = $dats[$key-1]['name'];
			else $dat['past'] = $dats[count($dats)-1]['name'];
			
			if ($key != count($dats)-1) $dat['next'] = $dats[$key+1]['name'];
			else $dat['next'] = $dats[0]['name'];
		}
	}
	
	$dat['next'] = strtr($dat['next'], " ", "-");
	$dat['past'] = strtr($dat['past'], " ", "-");
	
	$dat['longDescription'] = $dats[0]['longDescription'];
	
	$dat['catURL'] = str_replace(' ', '-', $dat['cat']);
	
	// Título de la página
	PageUtil::setVar('title', $dat['name'].' - '.$dat['cat']);
	
	// Obtener alto de imagen
	$image = 'modules/catalogo/pnimages/fotos/'.$dat['code'].'.jpg';
	$img = ImageCreateFromJpeg($image);
	$alto = ImageSY($img);
	$dat['height'] = $alto.'px';
	
	// Renderizando...
    $pnRender = pnRender::getInstance('catalogo');
	
	$pnRender->assign('dat', $dat);
	
    return $pnRender->fetch('catalogo_user_main.htm');
}

function catalogo_user_view($args=array())
{	
	// Obtener la categoría que se requier cargar (desde la url)
	$categoria = FormUtil::getPassedValue('cat', (isset($args['cat'])) ? $args['cat'] : 'agendas-de-bolsillo', 'GET');
	
	// Convertir de formato URL a común (Pasar a userapi)
	$categoria = strtr($categoria, "-", " ");
	
	// Obtener los datos de todos los productos de la categoría seleccionada.
	$dats = array();
	$pntable = pnDBGetTables();
    $catalogo = $pntable['catalogo_column'];
    $where = "WHERE $catalogo[cat] = '" . pnVarPrepForStore($categoria) . "'";
	$orderBy = "ORDER BY $catalogo[code]";
    $dats = DBUtil::selectObjectArray ('catalogo', $where, $orderBy);
	
	// Título de la página
	PageUtil::setVar('title', $dats[0]['cat'].$dats[0]['description']);
	
	// Obtener alto de imagen y fijar url con guiones
	foreach ($dats as $key => $value){
		$image = 'modules/catalogo/pnimages/fotos/'.$value['code'].'.jpg';
		$img = ImageCreateFromJpeg($image);
		$alto = ImageSY($img);
		$dats[$key]['height'] = $alto.'px';
		$dats[$key]['nameURL'] = str_replace(' ', '-', $dats[$key]['name']);
	}
	
	// Renderizando...
    $pnRender = pnRender::getInstance('catalogo');
	
	$pnRender->assign('dats', $dats);
	
    return $pnRender->fetch('catalogo_user_view.htm');
}

function catalogo_user_chekout()
{	
	// Título de la página
	PageUtil::setVar('title', 'Hacer pedido / Más información');
	
	Loader::requireOnce('modules/catalogo/pnincludes/catalogo_user_chekouthandler.class.php');
	
    // Create output object
    $pnf = FormUtil::newpnForm('catalogo');
	
	// Return the output that has been generated by this function
	return $pnf->pnFormExecute('catalogo_user_chekout.htm', new Catalogo_user_chekouthandler());
}

function catalogo_user_cotizacionsatisfactoria()
{	
	// Título de la página
	PageUtil::setVar('title', 'Cotización Satisfactoria');
	
	$dats = SessionUtil::getVar('cotizacionProcesada');
	SessionUtil::delVar('cotizacionProcesada');
	
	if(!$dats['id'] || empty($dats['id']))
		return pnRedirect(pnConfigGetVar('entrypoint', 'index.php'));
	
	// Renderizando...
    $pnRender = pnRender::getInstance('catalogo');
	$pnRender->assign('dats', $dats);
	
    return $pnRender->fetch('catalogo_user_cotizacionsatisfactoria.htm');
	
}